data:
  csv_file_path: /Users/seonghyunpark/Desktop/BoostCamp_Baseline/data/boostcamp_task1/data/train.csv
  image_dir_path: /Users/seonghyunpark/Desktop/BoostCamp_Baseline/data/boostcamp_task1/data/train
  predict_image_dir_path: /Users/seonghyunpark/Desktop/BoostCamp_Baseline/data/boostcamp_task1/data/test
  train_val_split: 0.8
  val_test_split: 0.7
  pin_memory: true
  train:
    batch_size: 64
    num_workers: 11
    shuffle: true
  val:
    batch_size: 32
    num_workers: 8
    shuffle: false
  test:
    batch_size: 1
    num_workers: 4
    shuffle: false
  predict:
    batch_size: 1
    num_workers: 4
    shuffle: false
