data_module: "src.data.custom_datamodules.image_classification.imageclassification_datamodule.ImageClassificationDataModule"
model_module: "src.plmodules.image_classification.image_classification_module.ImageClassificationModule"

data_config_path: "configs/data_configs/image_classification_contest.yaml"
augmentation_config_path: "configs/augmentation_configs/image_classification.yaml"

model:
  lr: 0.1
  in_channels: 3
  num_classes: 500

optimizer:
  name: Adam
  params:
    lr: 0.1

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1

callbacks:
  model_checkpoint:
    monitor: val_loss
    save_top_k: 3
    mode: min
  early_stopping:
    monitor: val_loss
    patience: 15
    mode: min

seed: 42  # 시드 값 추가
